NOTE: Use TOAD or SQLDeveloper to connect to the DB using the SYS/SYSTEM accounts. Logon to the DB as SYSDBA. Then run the following statements
***********************************************************************************************************************************************

create tablespace fog_computing datafile 'fog_computing.dat' size 100M autoextend on;

create user <PUT_YOUR_NAME_HERE> identified by <PUT_YOUR_PASSWORD_HERE> default tablespace fog_computing temporary tablespace temp;

grant create session to <PUT_YOUR_NAME_HERE>;
grant create table to <PUT_YOUR_NAME_HERE>;
grant sysdba to <PUT_YOUR_NAME_HERE>;

commit;

NOTE: After running the above statements, disconnect from the DB, and reconnect with the newly create UserID and Password and then continue running the statements below
************************************************************************************************************************************************************************
CREATE TABLE "SYS"."USER_TABLE" 
   (	"USER_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"USER_NAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"PWORD" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"EMAIL_ID" VARCHAR2(50 BYTE), 
	"MOBILE_NO" VARCHAR2(10 BYTE), 
	"ADDRESS" VARCHAR2(50 BYTE), 
	"START_TIME" DATE, 
	"END_TIME" DATE, 
	"SECURITY_QUESTION" VARCHAR2(50 BYTE), 
	"SECURITY_ANSWER" VARCHAR2(50 BYTE), 
	"USER_TYPE" VARCHAR2(20 BYTE), 
	"CREATION_DATE" DATE, 
	"START_HH" NUMBER(2,0), 
	"START_MM" NUMBER(2,0), 
	"END_HH" NUMBER(2,0), 
	"END_MM" NUMBER(2,0), 
	 PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
  
  CREATE TABLE "SYS"."FILE_TABLE" 
   (	"FILE_ID" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"FILE_NAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"FILE_TYPE" VARCHAR2(20 BYTE), 
	"USER_ID" VARCHAR2(20 BYTE), 
	"FILE_SIZE" NUMBER, 
	"UPLOAD_DATE" DATE, 
	"FILE_CONTENT" BLOB, 
	"DECOY_CONTENT" BLOB, 
	 PRIMARY KEY ("FILE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 FOREIGN KEY ("USER_ID")
	  REFERENCES "SYS"."USER_TABLE" ("USER_ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("FILE_CONTENT") STORE AS (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) 
 LOB ("DECOY_CONTENT") STORE AS (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) ;
  
  CREATE TABLE "SYS"."DOWNLOAD_TABLE" 
   (	"FILE_ID" VARCHAR2(10 BYTE), 
	"FILE_NAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"IS_SUCCESSFUL" VARCHAR2(1 BYTE), 
	"USER_ID" VARCHAR2(20 BYTE), 
	"DOWNLOAD_TIME" DATE, 
	 FOREIGN KEY ("FILE_ID")
	  REFERENCES "SYS"."FILE_TABLE" ("FILE_ID") ENABLE, 
	 FOREIGN KEY ("USER_ID")
	  REFERENCES "SYS"."USER_TABLE" ("USER_ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
  
  NOTE: Don't change the password field given below. It is an encoded text. It is 'oradba123'. That should be your Admin password.
  *****************************************************************************************************************************
  Insert into SYS.USER_TABLE (USER_ID,USER_NAME,PWORD,EMAIL_ID,MOBILE_NO,ADDRESS,START_TIME,END_TIME,SECURITY_QUESTION,SECURITY_ANSWER,USER_TYPE,CREATION_DATE,START_HH,START_MM,END_HH,END_MM) values ('U0004','<PUT_YOUR_NAME_HERE>','S7L4/F0GIBpQRZCUL+t4AA==','aritra@gmail.com','8801007207','Gachibowli',null,null,'What is your favourite color?','Black','Admin',to_date('21-FEB-16','DD-MON-RR'),2,3,4,4);