/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2016-03-05 16:06:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.JSPs;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class edit_005fuser_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("<head></head>\r\n");
      out.write("<body style=\"background:E4D1D1\">\r\n");
      out.write("\t<!-- ALL JAVA CODE HERE -->\r\n");
      out.write("\t");

		
	
      out.write("\r\n");
      out.write("\t<title>Edit User</title>\r\n");
      out.write("\t<div style=\"width:70%;top:0px;height:80px;left:230px;position:absolute\"><h1 align=\"center\">Fog Computing : Mitigating Insider Data Theft Attacks In the Cloud</h1></div>\r\n");
      out.write("\t<table style=\"width:10%;position:absolute;top:100px;height:80x;left:1055px;text-align:right\" align=\"center\">\r\n");
      out.write("\t\t<th><a href=\"#\">Go Back</a></th>\r\n");
      out.write("\t\t<th><a href=\"#\">Signout</a></th>\r\n");
      out.write("\t<table>\r\n");
      out.write("\t<div style=\"width:70%;top:140px;height:50px;left:230px;position:absolute;\"><h3 align=\"center\">Update User Details</h4></div>\r\n");
      out.write("\t<div style=\"width:70%;top:197px;height:50px;border-style:solid;left:230px;position:absolute;display:none\"><h4 align=\"center\">Some Message Abount Content Shown</h4></div>\r\n");
      out.write("\t<div style=\"width:34%;top:250px;height:350px;left:470px;position:absolute\">\r\n");
      out.write("\t<form>\r\n");
      out.write("\t\t<table style=\"width:40%;top:260px;left:476px;position:absolute\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Download Time</td>\r\n");
      out.write("\t\t\t\t<td>Start Hr</td>\r\n");
      out.write("\t\t\t\t<td>End Hr</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t<td><input name=\"startHH\" type=\"number\" min=\"0\" max=\"23\" value=\"00\"></td>\r\n");
      out.write("\t\t\t\t<td><input name=\"endHH\" type=\"number\" min=\"0\" max=\"23\" value=\"00\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Security Question 1</td>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t<select>\r\n");
      out.write("\t\t\t\t\t\t<option selected>Select your security question</option>\r\n");
      out.write("\t\t\t\t\t\t<option>What was the maiden name of your mother?</option>\r\n");
      out.write("\t\t\t\t\t\t<option>What was the brand of your first car?</option>\r\n");
      out.write("\t\t\t\t\t\t<option>What is your favourite movie?</option>\r\n");
      out.write("\t\t\t\t\t\t<option>What is your favourite color?</option>\r\n");
      out.write("\t\t\t\t\t\t<option>Who is your favourite politician?</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</td>\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Answer</td>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\"><input type=\"text\" size=\"36\"/></td>\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Security Question 1</td>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t<select>\r\n");
      out.write("\t\t\t\t\t\t<option selected>Select your security question</option>\r\n");
      out.write("\t\t\t\t\t\t<option>What was the maiden name of your mother?</option>\r\n");
      out.write("\t\t\t\t\t\t<option>What was the brand of your first car?</option>\r\n");
      out.write("\t\t\t\t\t\t<option>What is your favourite movie?</option>\r\n");
      out.write("\t\t\t\t\t\t<option>What is your favourite color?</option>\r\n");
      out.write("\t\t\t\t\t\t<option>Who is your favourite politician?</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</td>\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Answer</td>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\"><input type=\"text\" size=\"36\"/></td>\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Security Question 1</td>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t<select>\r\n");
      out.write("\t\t\t\t\t\t<option selected>Select your security question</option>\r\n");
      out.write("\t\t\t\t\t\t<option>What was the maiden name of your mother?</option>\r\n");
      out.write("\t\t\t\t\t\t<option>What was the brand of your first car?</option>\r\n");
      out.write("\t\t\t\t\t\t<option>What is your favourite movie?</option>\r\n");
      out.write("\t\t\t\t\t\t<option>What is your favourite color?</option>\r\n");
      out.write("\t\t\t\t\t\t<option>Who is your favourite politician?</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</td>\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Answer</td>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\"><input type=\"text\" size=\"36\"/></td>\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Security Question 1</td>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t<select>\r\n");
      out.write("\t\t\t\t\t\t<option selected>Select your security question</option>\r\n");
      out.write("\t\t\t\t\t\t<option>What was the maiden name of your mother?</option>\r\n");
      out.write("\t\t\t\t\t\t<option>What was the brand of your first car?</option>\r\n");
      out.write("\t\t\t\t\t\t<option>What is your favourite movie?</option>\r\n");
      out.write("\t\t\t\t\t\t<option>What is your favourite color?</option>\r\n");
      out.write("\t\t\t\t\t\t<option>Who is your favourite politician?</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</td>\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Answer</td>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\"><input type=\"text\" size=\"36\"/></td>\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Security Question 1</td>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t<select>\r\n");
      out.write("\t\t\t\t\t\t<option selected>Select your security question</option>\r\n");
      out.write("\t\t\t\t\t\t<option>What was the maiden name of your mother?</option>\r\n");
      out.write("\t\t\t\t\t\t<option>What was the brand of your first car?</option>\r\n");
      out.write("\t\t\t\t\t\t<option>What is your favourite movie?</option>\r\n");
      out.write("\t\t\t\t\t\t<option>What is your favourite color?</option>\r\n");
      out.write("\t\t\t\t\t\t<option>Who is your favourite politician?</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</td>\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Answer</td>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\"><input type=\"text\" size=\"36\"/></td>\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"3\" align=\"center\"><input type=\"submit\" value=\"Update User\"></td>\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
