/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2016-03-06 08:24:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.JSPs;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Iterator;
import com.fog.computing.pojo.File;
import java.util.List;

public final class user_005fhome_005fpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Iterator");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.fog.computing.pojo.File");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head></head>\r\n");
      out.write("<body style=\"background:E4D1D1\">\r\n");
      out.write("\t<!-- ALL JAVA CODE HERE -->\r\n");
      out.write("\t");

		String username = "user";
		String noFilesToDisplay = "display:none";
		String noTableToDisplay = "";
		List<File> fileList = null;
		if(session.getAttribute("username") != null){
			username = (String)session.getAttribute("username");
		}
		if(session.getAttribute("fileList") != null){
			fileList = (List<File>)session.getAttribute("fileList");
			if(fileList.size() == 0){
				noFilesToDisplay = "";
				noTableToDisplay = "display:none";
			}
		}
	
      out.write("\r\n");
      out.write("\t<title>User Home</title>\r\n");
      out.write("\t<div style=\"width:70%;top:0px;height:80px;left:230px;position:absolute\"><h1 align=\"center\">Fog Computing : Mitigating Insider Data Theft Attacks In the Cloud</h1></div>\r\n");
      out.write("\t<table style=\"width:50%;position:absolute;top:100px;height:80x;left:500px;text-align:right;\" align=\"center\">\r\n");
      out.write("\t\t<th><a href=\"");
      out.print(request.getContextPath());
      out.write("/Dispatcher?pageid=userhome&actionid=doFileUpload\">Upload File</a></th>\r\n");
      out.write("\t\t<th><a href=\"");
      out.print(request.getContextPath());
      out.write("/Dispatcher?pageid=userhome&actionid=doShowAboutUs\">About Us</a></th>\r\n");
      out.write("\t\t<th><a href=\"");
      out.print(request.getContextPath());
      out.write("/Dispatcher?pageid=userhome&actionid=doShowContactUs\">Contact Us</a></th>\r\n");
      out.write("\t\t<th><a href=\"");
      out.print(request.getContextPath());
      out.write("/Dispatcher?pageid=userhome&actionid=doShowAlerts\">View Alert</a></th>\r\n");
      out.write("\t\t<th><a href=\"");
      out.print(request.getContextPath());
      out.write("/Dispatcher?pageid=userhome&actionid=doChangePassword\">Change Password</a></th>\r\n");
      out.write("\t\t<th><a href=\"");
      out.print(request.getContextPath());
      out.write("/Dispatcher?pageid=userhome&actionid=doSignout\">Signout</a></th>\r\n");
      out.write("\t<table>\r\n");
      out.write("\t<div style=\"width:70%;top:140px;height:50px;left:230px;position:absolute;\"><h3 align=\"center\">Welcome ");
      out.print(username );
      out.write("</h4></div>\r\n");
      out.write("\t<div style=\"width:70%;top:197px;height:50px;left:230px;position:absolute;");
      out.print(noFilesToDisplay);
      out.write("\"><h4 align=\"center\">No files uploaded yet</h4></div>\r\n");
      out.write("\t<div style=\"width:70%;top:250px;height:500px;left:230px;position:absolute\">\r\n");
      out.write("\t\t<table style=\"width:70%;top:260px;left:233px;position:absolute;");
      out.print(noTableToDisplay);
      out.write("\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td style=\"border-style:solid\">Filename</td><td style=\"border-style:solid\">FileID</td><td style=\"border-style:solid\">Size</td><td style=\"border-style:solid\">Date Uploaded</td><td style=\"border-style:solid\">Download</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t");

				if(fileList != null){
					if(fileList.size() != 0){
						Iterator<File> iter = fileList.iterator();
						while(iter.hasNext()){
							File file = iter.next();	
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"border-style:solid\">");
      out.print(file.getFileName() );
      out.write("</td><td style=\"border-style:solid\">");
      out.print(file.getFileId() );
      out.write("</td><td style=\"border-style:solid\">");
      out.print(file.getFileSize() );
      out.write(" bytes</td><td style=\"border-style:solid\">");
      out.print(file.getUploadDate() );
      out.write("</td><td style=\"border-style:solid\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/Dispatcher?pageid=userhome&actionid=doFileDownload&fileid=");
      out.print(file.getFileId());
      out.write("\">Download</a></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t");

						}
					}
				}
			
      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
